// this file is auto generated by amalgamation.
// DO NOT EDIT this file.

#include "out.hpp"
/// main.cpp START

/// main.h START

#include<memory>
/// main.h END

#include<string>
int main(){
    /// not removed
    f();
    return 0;
}
/// main.cpp END
